name: Join Teams

on:
  workflow_dispatch:

jobs:

  join-teams:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run Team Join
        run: |
          python src/normalization/join_teams.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: games-teams
          path: data/normalized/games_teams/
