name: Merge Games CSV

on:
  workflow_dispatch:

jobs:
  merge-games:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pandas
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Merge season files
        run: |
          python src/normalization/merge_games.py

      - name: Upload merged seasons
        uses: actions/upload-artifact@v4
        with:
          name: season-games
          path: data/normalized/seasons/
